name: sms_telebot
description: "App to automatically forward incoming SMS messages to a Telegram bot."
publish_to: 'none'
version: 0.5.1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

# https://docs.flutter.dev/tools/pubspec